version: '3'
services:
  app:
    image: smith1984/vafs-app:0.0.1
    ports:
      - "8080:8080"
    depends_on:
      - fluent-bit
    env_file:
      - .env

  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "2020:2020"
    env_file:
      - .env
    volumes:
      - "./volumes/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf"
      - "./volumes/fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf"


  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:latest
    env_file:
      - .env
    ports:
      - '9200:9200'
      - '9600:9600'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "./volumes/opensearch/data:/usr/share/opensearch/data"

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    depends_on:
      - opensearch