version: '3'
services:
  app:
    image: smith1984/vafs-app:0.0.1
    ports:
      - "8080:8080"
    depends_on:
      - fluent-bit
      - liquibase
      - postgres
      - keycloak
    env_file:
      - .env
    volumes:
      - "./volumes/app/application.yaml:/app/resources/application.yaml"

  postgres-keycloak:
    image: postgres:15.2
    container_name: postgres-keycloak
    hostname: postgres-keycloak
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 15s
      interval: 5s
      retries: 10
    volumes:
      - "./volumes/postgres-keycloak/data:/data/postgres"
    env_file:
      - .env_keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command:
      - start-dev
    env_file:
      - .env_keycloak
    ports:
      - 8081:8080
    depends_on:
      - postgres-keycloak

  postgres:
    image: postgres:15.2
    container_name: postgres
    hostname: postgres
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 15s
      interval: 5s
      retries: 10
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - "./volumes/postgres/sql:/docker-entrypoint-initdb.d"
      - "./volumes/postgres/data:/data/postgres"

  liquibase:
    container_name: liquibase
    image: liquibase/liquibase:4.21.1
    depends_on:
      postgres:
        condition: service_healthy
    command: liquibase --url=jdbc:postgresql://postgres:5432/vafs?user=vafs --changelog-file=changelog.yaml update
    volumes:
      - "./volumes/postgres/liquidbase/changelog.yaml:/liquibase/changelog.yaml"

  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit:2.1.4
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "2020:2020"
    env_file:
      - .env_logging
    volumes:
      - "./volumes/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf"
      - "./volumes/fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf"


  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:2.7.0
    env_file:
      - .env_logging
    ports:
      - '9200:9200'
      - '9600:9600'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "./volumes/opensearch/data:/usr/share/opensearch/data:rw"

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.7.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    depends_on:
      - opensearch