package ru.beeline.vafs.common.stubs

enum class VafsStubs {
    NONE,
    SUCCESS,
    NOT_FOUND,
    BAD_ID,
    BAD_DESCRIPTION,
    BAD_PRIORITY,
    BAD_LIST_FOR_NUMBER_A,
    BAD_TYPE_OPERATION_A,
    BAD_LIST_FOR_NUMBER_B,
    BAD_TYPE_OPERATION_B,
    BAD_TYPE_OPERATION_COUNT,
    BAD_TARGET_COUNT,
    BAD_VALUE_IS_TRUE,
    BAD_TYPE_OPERATION_AB,
    BAD_TYPE_OPERATION_AB_COUNT,
    CANNOT_DELETE,
    BAD_SEARCH_STRING,
    DB_ERROR,
}
