ktor:
  deployment:
    port: 8080
  watch:
    - classes
    - resources
  application:
    modules:
      - "ru.beeline.vafs.ktor.ApplicationKt.module"
vafs:
  repository:
    test: memory
    prod: psql
    psql:
      password: "$POSTGRES_PASSWORD:vafs"
      schema: "backoffice"
      url: "$POSTGRES_URL:jdbc:postgresql://localhost:5432/vafs"
      user: "$POSTGRES_USER:vafs"
#jwt:
#  secret: "secret"
#  issuer: "beeline"
#  audience: "rule-users"
#  realm: "vafs-rules"
#  clientId: "beeline-vafs-service"

jwt:
  issuer: "$KC_ISSUER:http://localhost:8081/realms/beeline-vafs"
  audience: "rule-users"
  realm: "beeline-vafs"
  clientId: "beeline-vafs-service"
  certUrl: "$KC_CERT_URL:http://localhost:8081/realms/beeline-vafs/protocol/openid-connect/certs"
