openapi: 3.0.4
info:
  title: "Voice antifraud system log models"
  description: Log models for logging services of VAFS
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        rule:
          $ref: '#/components/schemas/VafsLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    VafsLogModel:
      title: Модель лога для микросервиса VAFS:rule
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - search
        requestRule:
          $ref: '#/components/schemas/RuleLog'
        requestFilter:
          $ref: '#/components/schemas/RuleFilterLog'
        responseRule:
          $ref: '#/components/schemas/RuleLog'
        responseRules:
          type: array
          items:
            $ref: '#/components/schemas/RuleLog'

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    RuleLog:
      title: Модель лога для объявления
      type: object
      properties:
        id:
          type: string
        description:
          type: string
        priority:
          type: integer
        listForNumberA:
          type: array
          items:
            type: string
        typeOperationA:
          type: string
        listForNumberB:
          type: array
          items:
            type: string
        typeOperationB:
          type: string
        typeOperationCount:
          type: string
        targetCount:
          type: integer
        valueIsTrue:
          type: boolean
        typeOperationAB:
          type: string
        typeOperationABCount:
          type: string
        userId:
          type: string
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string

    RuleFilterLog:
      title: Модель лога фильтра
      properties:
        searchString:
          type: string
        userId:
          type: string

